version: '3.8'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: zide-website-prd
    image: $IMAGE_NAME
    restart: unless-stopped
    networks:
      - zide-traefik-n
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=zide-traefik-n'
      - 'traefik.http.services.${PROJECT_NAME}.loadbalancer.server.port=80'

      - 'traefik.http.routers.${PROJECT_NAME}-https.rule=Host(`${ENVIRONMENT_URL}`) || Host(`www.${ENVIRONMENT_URL}`)'
      - 'traefik.http.routers.${PROJECT_NAME}-https.entrypoints=websecure'
      - 'traefik.http.routers.${PROJECT_NAME}-https.tls.certresolver=zideresolver'
      - 'traefik.http.routers.${PROJECT_NAME}-https.service=${PROJECT_NAME}'

      - 'traefik.http.routers.${PROJECT_NAME}-http.rule=Host(`${ENVIRONMENT_URL}`) || Host(`www.${ENVIRONMENT_URL}`)'
      - 'traefik.http.routers.${PROJECT_NAME}-http.entrypoints=web'
      - 'traefik.http.routers.${PROJECT_NAME}-http.service=${PROJECT_NAME}'

      - 'io.portainer.accesscontrol.teams=zide'
    environment:
      - DOCKER_IMAGE_NAME

networks:
  zide-traefik-n:
    external: true
